sudo: true

language: python

python:
- "3.5"
- "3.6"

install:
- pip install pytest pytest-cov codecov coverage
- pip install -r requirements.txt

before_script:
- python setup.py install

script:
- py.test --cov-report term-missing --cov=netneurotools

after_success:
- codecov
